package com.example.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.model.Girl;
import com.example.repository.GirlRepository;

import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
public class GirlService {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private GirlRepository grilRepository;
	
	public List<Girl> findAll(){
		return grilRepository.findAll();
	}
	
}
