package com.example.repository;


import static org.junit.Assert.assertNotNull;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.junit4.SpringRunner;

import com.example.model.Girl;

import lombok.extern.slf4j.Slf4j;
@RunWith(SpringRunner.class)
@DataJpaTest
@Slf4j
@TestPropertySource(locations = "classpath:test.properties")
public class GirlRepositoryTest {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private GirlRepository grilRepository;

	@Before
	public void setup() {
		Girl girl = Girl.builder().age(10).cupSize("B").build();
		grilRepository.save(girl);
	}
	
	@Test
	public void getAll() {
		Girl girl = grilRepository.getOne(1);
		assertNotNull(girl);
	}

}
